---
jobs:
- name: set-self
  plan:
  - in_parallel:
    - get: sandbox-source
      trigger: true
  - set_pipeline: purge-sandboxes
    file: sandbox-source/ci/pipeline.yml

- name: test
  plan:
  - in_parallel:
    - get: sandbox-source
      trigger: true
      passed: [set-self]
    - get: general-task
  - task: test
    image: general-task
    file: sandbox-source/ci/test.yml

- name: purge-sandboxes-staging
  plan:
  - in_parallel:
    - get: sandbox-source
      passed: [test]
    - get: schedule
      trigger: true
    - get: general-task
      
  - task: purge
    file: sandbox-source/ci/purge.yml
    image: general-task
    params:
      API_ADDRESS: ((staging-cf-api-url))
      CLIENT_ID: ((client-id-staging))
      CLIENT_SECRET: ((client-secret-staging))
      ORG_PREFIX: ((org-prefix))
      NOTIFY_DAYS: ((notify-days))
      PURGE_DAYS: ((purge-days))
      NOTIFY_MAIL_SUBJECT: ((notify-subject))
      PURGE_MAIL_SUBJECT: ((purge-subject))
      SMTP_HOST: ((smtp-host))
      SMTP_USER: ((smtp-user))
      SMTP_PASS: ((smtp-pass))
      SMTP_PORT: ((smtp-port))
      SMTP_CERT: ((smtp-cert))
      MAIL_SENDER: ((smtp-from))
      TIME_STARTS_AT: ((time-starts-at-staging))
      DRY_RUN: ((dry-run-staging))
  on_failure:
    put: slack
    params: &slack-params
      text: |
        :x: FAILED to notify sandbox users on staging
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel-failure))
      username: ((slack-username))
      icon_url: ((slack-icon-url))
  on_success:
    put: slack
    params:
      <<: *slack-params
      channel: ((slack-channel-success))
      text: |
        :white_check_mark: Successfully notified sandbox users on staging
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>

- name: purge-sandboxes-production
  plan:
  - in_parallel:
    - get: sandbox-source
      passed: [purge-sandboxes-staging]
    - get: schedule
      trigger: true
    - get: general-task
  - task: purge
    file: sandbox-source/ci/purge.yml
    image: general-task
    params:
      API_ADDRESS: ((prod-cf-api-url))
      CLIENT_ID: ((client-id-production))
      CLIENT_SECRET: ((client-secret-production))
      ORG_PREFIX: ((org-prefix))
      NOTIFY_DAYS: ((notify-days))
      PURGE_DAYS: ((purge-days))
      NOTIFY_MAIL_SUBJECT: ((notify-subject))
      PURGE_MAIL_SUBJECT: ((purge-subject))
      SMTP_HOST: ((smtp-host))
      SMTP_USER: ((smtp-user))
      SMTP_PASS: ((smtp-pass))
      SMTP_PORT: ((smtp-port))
      SMTP_CERT: ((smtp-cert))
      MAIL_SENDER: ((smtp-from))
      TIME_STARTS_AT: ((time-starts-at-production))
      DRY_RUN: ((dry-run-production))
  on_failure:
    put: slack
    params:
      <<: *slack-params
      channel: ((slack-channel-failure))
      text: |
        :x: FAILED to notify sandbox users on production
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
  on_success:
    put: slack
    params:
      <<: *slack-params
      channel: ((slack-channel-success))
      text: |
        :white_check_mark: Successfully notified sandbox users on production
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>

resources:
- name: sandbox-source
  type: git
  source:
    commit_verification_keys: ((cloud-gov-pgp-keys))
    uri: https://github.com/cloud-gov/cg-sandbox
    branch: fix-panic

- name: schedule
  type: cron-resource
  source:
    expression: ((schedule-expression))
    location: ((schedule-location))

- name: slack
  type: slack-notification
  source:
    url: ((slack-webhook-url))

- name: general-task
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: general-task
    aws_region: us-gov-west-1
    tag: latest

resource_types:
- name: registry-image
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: registry-image-resource
    aws_region: us-gov-west-1
    tag: latest

- name: cron-resource
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: cron-resource
    aws_region: us-gov-west-1
    tag: latest

- name: git
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: git-resource
    aws_region: us-gov-west-1
    tag: latest

- name: slack-notification
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: slack-notification-resource
    aws_region: us-gov-west-1
    tag: latest
